repos:
  - repo: local
    hooks:
      - id: chartkit-version-check
        name: chartkit
        entry: uv run --directory ./scripts chartkit version check
        files: \.((ya?ml)|(tpl))$
        language: python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-format # formatter
        types_or: [python, pyi, jupyter, toml]
      - id: ruff-check # linter
        types_or: [python, pyi, jupyter, toml]
        args: [--fix]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
  - repo: local
    hooks:
      - id: helm-unittest
        name: helm unittest
        entry: make unit-tests
        files: '^.*\/(application|library)\/.*(\.yaml|\.tpl)$'
        language: system
        pass_filenames: false
