{{- define "workload.configMap" -}}
{{- $config_maps := default (dict) .configMaps }}
{{- $name_override := default "" .nameOverride }}
{{- $params := list }}
{{- range $name, $config := $config_maps }}
  {{- if $name_override }}
    {{- $name = $name_override }}
  {{- end }}
  {{- $_ := set $config "name" $name }}
  {{- /* Configure Argo CD annotations */}}
  {{- $annotation_params := dict "config" $config "type" "configMap" }}
  {{- $argo_annotations := include "workload.config.argo.annotations" $annotation_params | fromYaml }}
  {{- $_ = set $config "annotations" (mergeOverwrite (default (dict) $annotation_params.config.annotations) $argo_annotations) }}
  {{- $params = append $params $config }}
{{- end }}
{{- $params := mergeOverwrite (. | deepCopy) (dict "configMaps" $params) }}
{{- include "common.configMap" $params }}
{{- end -}}
